services:
  gateway-proxy:
    container_name: gateway-proxy
    image: ghcr.io/onixldlc/proxy-mirror:latest
    ports:
      - "3000:3000"
    volumes:
      - ./conf:/app/conf:ro
    restart: unless-stopped