services:
  gateway-proxy:
    container_name: gateway-proxy
    image: ghcr.io/onixldlc/proxy-mirror:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/app/conf:ro
      - ./certs:/app/certs
    environment:
      - HTTP_PORT=80          # optional
      - HTTPS_PORT=443        # optional
      - CONF_DIR=/app/conf    # optional
      - CERTS_DIR=/app/certs  # optional
    restart: unless-stopped
